# Site
repository: dhuzard/cv2
favicon: images/favicon.ico

# Content configuration version
version: 1

# Personal info
name: Damien Huzard
title: Neuroscience PhD
# email: damien.huzard@gmail.com
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: true

# Social links
# Social links
twitter_username: dhuzard
github_username:  dhuzard
# dribbble_username:
# facebook_username:
# flickr_username:
# instagram_username:
linkedin_username: damien-huzard
# pinterest_username:
# youtube_username:
# googleplus_username:
orcid_username: 0000-0003-4820-7951

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpeg
about_content: |
  Hi, my name is Roberto De Filippo, I am a neuroscientist interested in the effect of neuromodulators (and various hallucinogenic drugs) on sensory perception. 
  Currently my main focus is <mark>serotonin</mark>, in vivo recordings with high-density probes (Neuropixel) and Machine Learning in the context of neural decoding.
  I have experience working with:
  <mark>Python</mark> (<mark>pandas</mark>, <mark>xarray</mark>, <mark>numpy</mark>, <mark>HoloViz</mark>), 
  <mark>Matlab</mark>,
  <mark>Tensorflow</mark>,
  <mark>Max/MSP</mark>,
  <mark>Pure Data</mark> and
  <mark>git</mark>.

content:
  - title: Lab Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Bourinet lab, Inserm, Institut de Génomique Fonctionnelle (IGF), Montpellier
        link: https://www.igf.cnrs.fr/index.php/en/h-teams-en/ht-bourinet-en
        # link_text: boringcompany.com
        sub_title: Postdoc #2
        caption: July 2021 - present
        #quote: > Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            My PhD project is focused on serotonergic modulation of slow oscillations in entorhinal cortex, it led to the publication 
            "Somatostatin interneurons activated by 5-HT<sub>2A</sub> receptor suppress slow oscillations in medial entorhinal cortex (Elife, 2021)". 
            We identified a novel mechanism by which serotonin is able to alter cortical network activity. During the course of this project I employed the following techniques: 
            in vitro patch clamp, silicone probe recording in anesthetized mice, optogenetics, 
            pharmacology, immunohistochemistry and confocal imaging. I also became proficient with Matlab and Python for data analysis.

      - layout: right
        title: Poulet lab, Max Delbrück Center (MDC)
        link: https://www.mdc-berlin.de/poulet
         # link_text: boringcompany.com
        sub_title: PhD student
        caption: February 2015 - December 2015
        #quote: >
        #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            I worked under the supervision of Nevena Milenkovic investigating temperature perception in mice, a follow-up to her work 
            "A somatosensory circuit for cooling perception in mice (Nature Neuroscience, 2014)". I have performed in vivo whole cell patch clamp recording from anesthetized mice,
            thalamic drug injections and behavioral training.

      - layout: left
        title: Brecht lab, Bernstein Center for Computational Neuroscience (BCCN)
        link: https://www.activetouch.de/
        # link_text: boringcompany.com
        sub_title: Lab rotation
        caption: October 2014 - January 2015
          #quote: >
          #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
                During my lab rotation in the Brecht lab I assisted Dr. Shimpei Ishiyama in his project later published as 
                "Neural correlates of ticklishness in the rat somatosensory cortex (Science, 2016)".
                The aim of his project was to understand the neurophysiological basis of ticklishness. 
                My work was to assess if rats, like humans, have body areas more susceptible to tickling compared to others. 
                A Matlab-based system was used to record 50-kHz USVs (ultra-sonic vocalization). 
                USVs emission rate was used as a measure of ticklishness. 
                In addition to this psychophysics experiment I assisted to in vivo tetrodes recording and electrical microstimulation in S1. 

      - layout: right
        title: Cherubini lab, International School for Advanced Studies (SISSA).
        link: https://www.sissa.it/
        # link_text: boringcompany.com
        sub_title: Master student
        caption: July 2012 - October 2013
          #quote: >
          #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
                I did my internship in Professor Enrico Cherubini's lab working as an in vitro electrophysiologist. 
                My thesis focused on the cis-trans isomerase Pin1 role in excitatory synaptic signaling. 
                I recorded, using the whole-cell configuration of the patch clamp technique, CA1 pyramidal cells in mouse brain slices 
                while stimulating the Schaﬀer collaterals and applying selective blockers of GABAA, AMPA and NMDA receptors.
                I performed post-hoc morphological reconstruction on a subset of neurons using biocytin and confocal microscopy. 
                My experiments contributed to the publication of “Pin1 Modulates the Synaptic Content of NMDA Receptors via Prolyl-Isomerization 
                of PSD-95 (Journal of Neuroscience, 2016)”
         
         

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: University of Trieste
        caption: October 2011 - October 2013
        sub_title: Master's degree in Neuroscience
        quote: >
          110/110 cum laude
        # description: | # this will include new lines to allow paragraphs
         # During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

         # I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

      - layout: top-middle
        title: University of Milan
        caption: October 2008 - October 2011
        sub_title: Bachelor's degree in Biology
        quote: >
             103/110 
        # description: | # this will include new lines to allow paragraphs
        #  During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

        #  I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: Publications
    layout: text
    content: | # this will include new lines to allow paragraphs
       - **Somatostatin interneurons activated by 5-HT<sub>2A</sub> receptor suppress slow oscillations in medial entorhinal cortex.**\
        Elife. 2021 Mar 31;10:e66960. doi: 10.7554/eLife.66960. PMID: 33789079; PMCID: PMC8016478.\
        de Filippo R<sup>*</sup>, Rost BR, Stumpf A, Cooper C, Tukker JJ, Harms C, Beed P, Schmitz D<sup>*</sup>.\
        <sup>*</sup> = corresponding authors


        - **Layer 3 Pyramidal Cells in the Medial Entorhinal Cortex Orchestrate Up-Down States and Entrain the Deep Layers Differentially.** \
        Cell Rep. 2020 Dec 8;33(10):108470. doi: 10.1016/j.celrep.2020.108470. PMID: 33296656.\
        Beed P<sup>*</sup>, de Filippo R<sup>*</sup>, Holman C<sup>*</sup>, Johenning FW, Leibold C, Caputi A, Monyer H, Schmitz D.\
        <sup>*</sup> = equal contribution

        - **Pin1 Modulates the Synaptic Content of NMDA Receptors via Prolyl-Isomerization of PSD-95.** \
        J Neurosci. 2016 May 18;36(20):5437-47. doi: 10.1523/JNEUROSCI.3124-15.2016. PMID: 27194325; PMCID: PMC6601765.\
        Antonelli R, De Filippo R, Middei S, Stancheva S, Pastore B, Ammassari-Teule M, Barberis A, Cherubini E, Zacchi P. 

  - title: Conferences
    layout: text
    content: | # this will include new lines to allow paragraphs
        - **2019** INSIGHT, Berlin. Poster ‘Serotonergic modulation of slow oscillations’ 
        - **2018** FENS, Berlin. Poster ‘Serotonergic modulation of slow oscillations’

  - title: Awards
    layout: text
    content: | # this will include new lines to allow paragraphs
        - **2015** Neurocure fellowship

  - title: Various interests
    layout: text
    content: | # this will include new lines to allow paragraphs
        <p style="text-align:center">
          <img src="/images/synths.jpeg " width="300" title="synthesizers"/>
          <img src="/images/IMG_8581.jpg" width="400" title="nice beaches"/> 
          <img src="/images/IMG_5849.jpeg " width="400" title="skates"/>
        </p>
        <p style="text-align:center">
          <img src="/images/IMG_5850.jpeg " width="300" title="playing guitar"/>
          <img src="/images/waterfall.gif " width="450" title="visiting waterfalls"/>
          <img src="/images/geyser.gif " width="300" title="watching geysers from really near"/>
        </p>
        <p style="text-align:center">
          <img src="/images/Arduino_UNO_WIFI_30117100-01.jpeg " width="330" title="arduinos"/>
          <img src="/images/V2Y0.gif " width="330" title="cinema"/>
          <img src="/images/philosophy.jpeg " width="330" title="philosophy"/>
        </p>
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
